### PR TITLE
Fix ULogs.IsIP Function

### PR DESCRIPTION
**Pull request by MexicanRaindeer**
Fixes the ULogs.IsIP Function

### CODE REVIEW

**Comment by myrage2000** [comment]
Hey, Did you try it ?
Does it work with IPs like xxx.xxx.xxx.xxx ?
And with other IPs like xxx.xxx.xx.xx ?
I mean does it work with less than 3 digits ?

**Comment by MexicanRaindeer** [comment]
Well, I tried to try it but the GUI is broken for me... I looked through the code and didn't find any problems either & no errors. I can adapt it to check for "xxx.xxx.xxx.xxx & xxx.xxx.xx.xx"

**Comment by MexicanRaindeer** [comment]
It now supports those IP types and ignores IPs that are invalid/fake

**Comment by myrage2000** [comment]
I'll try it
Thanks for your contribution

**Comment by MexicanRaindeer** [comment]
Any updates on this? I was wondering if it worked?

**Comment by myrage2000** [comment]
Hey !
A update is finally coming !
I can't merge it because it's too old now, but I copied your regex to my local version !
I will give you credit for it in the file, of course.

Thanks !

**Pull request closed without merging**
